#!/bin/bash

# initialize DoodleIsabellaPlugin sketch
./doodle sketch init sketch_one com.bushpath.doodle.isabella.IsabellaPlugin dht
./doodle sketch modify sketch_one \
	-a "feature:albedo_surface:-1" \
    -a "feature:categorical_freezing_rain_yes1_no0_surface:-1" \
    -a "feature:categorical_ice_pellets_yes1_no0_surface:-1" \
    -a "feature:categorical_rain_yes1_no0_surface:-1" \
    -a "feature:categorical_snow_yes1_no0_surface:-1" \
    -a "feature:convective_available_potential_energy_surface:-1" \
    -a "feature:convective_inhibition_surface:-1" \
    -a "feature:direct_evaporation_cease_soil_moisture_surface:-1" \
    -a "feature:downward_long_wave_rad_flux_surface:-1" \
    -a "feature:downward_short_wave_rad_flux_surface:-1" \
    -a "feature:drag_coefficient_surface:-1" \
    -a "feature:friction_velocity_surface:-1" \
    -a "feature:geopotential_height_lltw:-1" \
    -a "feature:geopotential_height_pblri:-1" \
    -a "feature:geopotential_height_surface:-1" \
    -a "feature:geopotential_height_zerodegc_isotherm:-1" \
    -a "feature:ice_cover_ice1_no_ice0_surface:-1" \
    -a "feature:land_cover_land1_sea0_surface:-1" \
    -a "feature:latent_heat_net_flux_surface:-1" \
    -a "feature:lightning_surface:-1" \
    -a "feature:maximumcomposite_radar_reflectivity_entire_atmosphere:-1" \
    -a "feature:mean_sea_level_pressure_nam_model_reduction_msl:-1" \
    -a "feature:missing_pblri:-1" \
    -a "feature:number_of_soil_layers_in_root_zone_surface:-1" \
    -a "feature:planetary_boundary_layer_height_surface:-1" \
    -a "feature:plant_canopy_surface_water_surface:-1" \
    -a "feature:precipitable_water_entire_atmosphere:-1" \
    -a "feature:pressure_maximum_wind:-1" \
    -a "feature:pressure_reduced_to_msl_msl:-1" \
    -a "feature:pressure_surface:-1" \
    -a "feature:pressure_tropopause:-1" \
    -a "feature:relative_humidity_zerodegc_isotherm:-1" \
    -a "feature:sensible_heat_net_flux_surface:-1" \
    -a "feature:snow_cover_surface:-1" \
    -a "feature:snow_depth_surface:-1" \
    -a "feature:soil_porosity_surface:-1" \
    -a "feature:soil_type_as_in_zobler_surface:-1" \
    -a "feature:surface_roughness_surface:-1" \
    -a "feature:surface_wind_gust_surface:-1" \
    -a "feature:temperature_surface:-1" \
    -a "feature:temperature_tropopause:-1" \
    -a "feature:total_cloud_cover_entire_atmosphere:-1" \
    -a "feature:transpiration_stress-onset_soil_moisture_surface:-1" \
    -a "feature:u-component_of_wind_maximum_wind:-1" \
    -a "feature:u-component_of_wind_pblri:-1" \
    -a "feature:u-component_of_wind_tropopause:-1" \
    -a "feature:upward_long_wave_rad_flux_surface:-1" \
    -a "feature:upward_short_wave_rad_flux_surface:-1" \
    -a "feature:v-component_of_wind_maximum_wind:-1" \
    -a "feature:v-component_of_wind_pblri:-1" \
    -a "feature:v-component_of_wind_tropopause:-1" \
    -a "feature:vegetation_surface:-1" \
    -a "feature:vegitation_type_as_in_sib_surface:-1" \
    -a "feature:visibility_surface:-1" \
    -a "feature:water_equiv_of_accum_snow_depth_surface:-1" \
    -a "feature:wilting_point_surface:-1" \
    -a "knotCount:-1:6"
