#!/bin/sh
APPLICATION="doodle-fds"
VERSION="0.1-SNAPSHOT"
MAIN_CLASS="com.bushpath.doodle.dfs.Main"

CLASSPATH=""
BASEDIR=$(dirname $0)
if [ -f $BASEDIR/build/libs/$APPLICATION-$VERSION.jar ]; then
    CLASSPATH="$BASEDIR/build/libs/$APPLICATION-$VERSION.jar"
else
    echo "unable to find $APPLICATION-$VERSION.jar."
    exit 1
fi

JAVA_OPTS="-Dorg.slf4j.simpleLogger.defaultLogLevel=info --illegal-access=deny -Djava.library.path=$BASEDIR/libs/anamnesis-jni/"

java -cp $CLASSPATH $JAVA_OPTS $MAIN_CLASS $@
