nodeId = 1
ipAddress = "127.0.0.1"
port = 5451
serverThreadCount = 4

#
# Control Plane Configuration
#
[control]
directory = "../persist/1/control"

[control.journal]
directory = "../persist/1/control-journal"
maximumFileSizeBytes = 2097152

#
# Data Plane Configuration
#
[data]
directory = "../persist/1/data"

[data.replication]
intervalMilliSeconds = 1000

[data.journal]
directory = "../persist/1/data-journal"
maximumFileSizeBytes = 67108864

#
# FileSystem Configuration
#
[filesystem]
workerThreadCount = 4

[filesystem.namenode]
ipcPort = 9001

[filesystem.datanode]
xferPort = 8021
ipcPort = 8031
infoPort = 8041

#
# Gossip Configuration
#
[gossip]
intervalMilliSeconds = 2500
 
[[gossip.seed]]
ipAddress = "127.0.0.1"
port = 5450

#
# Memory Management Configuration
#
[memoryManagement]
intervalMilliSeconds = 1000
writeDiffMilliSeconds = 10000

#
# Plugins Configuration
#
[plugins]
directory = "../plugins"
