nodeId = 0
ipAddress = "127.0.0.1"
port = 5450
serverThreadCount = 4

#
# Control Plane Configuration
#
[control]
directory = "../persist/0/control"

[control.journal]
directory = "../persist/0/control-journal"
maximumFileSizeBytes = 2097152

#
# Data Plane Configuration
#
[data]
directory = "../persist/0/data"

[data.replication]
intervalMilliSeconds = 1000

[data.journal]
directory = "../persist/0/data-journal"
maximumFileSizeBytes = 67108864

#
# FileSystem Configuration
#
[filesystem]
workerThreadCount = 4

[filesystem.namenode]
ipcPort = 9000

[filesystem.datanode]
xferPort = 8020
ipcPort = 8030
infoPort = 8040

#
# Gossip Configuration
#
[gossip]
intervalMilliSeconds = 2500
 
[[gossip.seed]]
ipAddress = "127.0.0.1"
port = 5451

#
# Memory Management Configuration
#
[memoryManagement]
intervalMilliSeconds = 1000
writeDiffMilliSeconds = 10000

#
# Plugins Configuration
#
[plugins]
directory = "../plugins"
