threadCount = 4

#
# Control Plane Configuration
#
[control]
nodeId = 0
ipAddress = "127.0.0.1"
port = 5450
 
[control.gossip]
intervalMilliSeconds = 2500
 
[[control.gossip.seed]]
ipAddress = "127.0.0.1"
port = 5451

[control.replication]
intervalMilliSeconds = 1000

#
# FileSystem Configuration
#
[filesystem]
threadCount = 4

[filesystem.namenode]
ipcPort = 9000

[filesystem.datanode]
xferPort = 8020
ipcPort = 8030
infoPort = 8040

#
# Plugins Configuration
#
[plugins]
directory = "../plugins"
