nodeId = 1
ipAddress = "127.0.0.1"
port = 5451
serverThreadCount = 4

#
# Control Plane Configuration
#
[control.journal]
directory = "../journal/control"
maximumFileSizeBytes = 8589934592

#
# Data Plane Configuration
#
[data.replication]
intervalMilliSeconds = 1000

[data.journal]
directory = "../journal/data"
maximumFileSizeBytes = 68719476736

#
# FileSystem Configuration
#
[filesystem]
workerThreadCount = 4

[filesystem.namenode]
ipcPort = 9001

[filesystem.datanode]
xferPort = 8021
ipcPort = 8031
infoPort = 8041

#
# Gossip Configuration
#
[gossip]
intervalMilliSeconds = 2500
 
[[gossip.seed]]
ipAddress = "127.0.0.1"
port = 5450

#
# Plugins Configuration
#
[plugins]
directory = "../plugins"
