#
# Control Plane Configuration  
#
[control]
nodeId = 1                     
ipAddress = "127.0.0.1"        
port = 5451                    
threadCount = 4                
  
[control.gossip]
intervalMilliSeconds = 2500    
          
[[control.gossip.seed]]
ipAddress = "127.0.0.1"
port = 5450
        
#       
# Sketch Plane Configuration   
#       
[sketch.checkpoint]
directory = "."
transferIntervalMilliSeconds = 2000

#   
# Plugins Configuration        
# 
[plugins]
directory = "../plugins"
