threadCount = 4

#
# Control Plane Configuration
#
[control]
nodeId = 1
ipAddress = "127.0.0.1"
port = 5451
 
[control.gossip]
intervalMilliSeconds = 2500
 
[[control.gossip.seed]]
ipAddress = "127.0.0.1"
port = 5450

#
# FileSystem Configuration
#
[filesystem]
threadCount = 4

[filesystem.namenode]
ipcPort = 9001

[filesystem.datanode]
xferPort = 8021
ipcPort = 8031
infoPort = 8041

#
# Plugins Configuration
#
[plugins]
directory = "../plugins"
 
#
# Sketch Plane Configuration
#
[sketch.checkpoint]
directory = "../checkpoints/1/"

[sketch.checkpoint.transfer]
intervalMilliSeconds = 2000
bufferSizeBytes = 8192
