threadCount = 4

#
# Control Plane Configuration
#
[control]
nodeId = 2
ipAddress = "127.0.0.1"
port = 5452
 
[control.gossip]
intervalMilliSeconds = 2500
 
[[control.gossip.seed]]
ipAddress = "127.0.0.1"
port = 5450

[control.replication]
intervalMilliSeconds = 1000

#
# FileSystem Configuration
#
[filesystem]
threadCount = 4

[filesystem.namenode]
ipcPort = 9002

[filesystem.datanode]
xferPort = 8022
ipcPort = 8032
infoPort = 8042

#
# Plugins Configuration
#
[plugins]
directory = "../plugins"
