nodeId = 3
ipAddress = "127.0.0.1"
port = 5453
serverThreadCount = 4

#
# Control Plane Configuration
#
[control]
directory = "../persist/3/control"

[control.journal]
directory = "../persist/3/control-journal"
maximumFileSizeBytes = 2097152

#
# Data Plane Configuration
#
[data]
directory = "../persist/3/data"

[data.replication]
intervalMilliSeconds = 1000

[data.journal]
directory = "../persist/3/data-journal"
maximumFileSizeBytes = 67108864

#
# FileSystem Configuration
#
[filesystem]
workerThreadCount = 4

[filesystem.namenode]
ipcPort = 9003

[filesystem.datanode]
xferPort = 8023
ipcPort = 8033
infoPort = 8043

#
# Gossip Configuration
#
[gossip]
intervalMilliSeconds = 2500
 
[[gossip.seed]]
ipAddress = "127.0.0.1"
port = 5450

#
# Plugins Configuration
#
[plugins]
directory = "../plugins"
