threadCount = 4

#
# Control Plane Configuration
#
[control]
nodeId = 3
ipAddress = "127.0.0.1"
port = 5453
 
[control.gossip]
intervalMilliSeconds = 2500
 
[[control.gossip.seed]]
ipAddress = "127.0.0.1"
port = 5450

#
# FileSystem Configuration
#
[filesystem]
threadCount = 4

[filesystem.namenode]
ipcPort = 9003

[filesystem.datanode]
xferPort = 8023
ipcPort = 8033
infoPort = 8043

#
# Plugins Configuration
#
[plugins]
directory = "../plugins"
 
#
# Sketch Plane Configuration
#
[sketch.checkpoint]
directory = "../checkpoints/3/"

[sketch.checkpoint.transfer]
intervalMilliSeconds = 2000
bufferSizeBytes = 8192
