ipAddress = "127.0.0.1"
port = 5550
serverThreadCount = 2

#
# FileSystem Configuration
#
[filesystem]
workerThreadCount = 3

[filesystem.namenode]
ipcPort = 9000

[filesystem.datanode]
xferPort = 8020
ipcPort = 8030
infoPort = 8040

#
# Gossip Configuration
#
[gossip]
intervalMilliSeconds = 2500
 
[[gossip.seed]]
ipAddress = "127.0.0.1"
port = 5451

#
# Memory Management Configuration
#
[memoryManagement]
intervalMilliSeconds = 1000
writeDiffMilliSeconds = 10000

#
# Plugins Configuration
#
[plugins]
directory = "../plugins"
