#!/bin/sh
APPLICATION="doodle"
VERSION="0.1-SNAPSHOT"
MAIN_CLASS="com.bushpath.doodle.cli.Main"

JAVA_OPTS="-Dorg.slf4j.simpleLogger.defaultLogLevel=info"

CLASSPATH=""
BASEDIR=$(dirname $0)
if [ -f $BASEDIR/build/libs/$APPLICATION-$VERSION.jar ]; then
    CLASSPATH="$BASEDIR/build/libs/$APPLICATION-$VERSION.jar"
else
    echo "unable to find $APPLICATION-$VERSION.jar."
    exit 1
fi

java -cp $CLASSPATH $JAVA_OPTS $MAIN_CLASS $@
